### PR TITLE
Update AUTHORS

### PR DESCRIPTION
**Pull request by SabineAuer**

### CODE REVIEW

**Comment by timkittel** [comment]
ci not passing

**Comment by SabineAuer** [comment]
The travis CI build failed with 

> You didn't provide the details of your change in CHANGELOG.md

The CHANGELOG.md is new to me. What details shall I provide here?

**Comment by timkittel** [comment]
There are already entries in the [CHANGELOG.md](https://github.com/JuliaEnergy/PowerDynBase.jl/blob/master/CHANGELOG.md), just do it similarly.

**Comment by SabineAuer** [comment]
OK, I updated the [CHANGELOG.md](https://github.com/JuliaEnergy/PowerDynBase.jl/blob/master/CHANGELOG.md) file

**Comment by timkittel** [comment]
The ci is failing again?

I wouldn't call the addition of an author an enhancement. Maybe make a new shield and call it PD|miscellaneous?

**Comment by SabineAuer** [comment]
I can change the tag if you prefer so.
Concerning the CI failing I found this issue: https://github.com/JuliaWeb/MbedTLS.jl/issues/193 since this was my error message [julia: symbol lookup error: /home/travis/.julia/packages/MbedTLS/XkQiX/deps/usr/lib/libmbedtls.so: undefined symbol: mbedtls_x509_crt_verify_restartable](https://travis-ci.org/JuliaEnergy/PowerDynBase.jl/jobs/490459628#L634)

**Comment by SabineAuer** [comment]
I think, this is a problem with Julia 1.1 version since the Travis CI for Julia 1.0 is passing and the Changelog part as well.

**Comment by timkittel** [comment]
okai, then I would merge this. @SabineAuer can you open a pull request to fix the ci temporarily, e.g. by fixing the version of MbedTLS.jl?

**Comment by timkittel** [comment]
The travis fix should really have highest prio now.

**Comment by SabineAuer** [comment]
I agree, though as far as I can see the issue, I referenced, is still open. I am following it to stay updated.

**Comment by timkittel** [comment]
yep, but you could simply submit a PR that restricts the version of MbedTLS.jl on travis. (Note, not in the Project.toml.)

**Pull request merged**
